export const productsData = [
  {
    id: 1,
    title: "Product 1",
    description: "This is the description for Product 1.",
    price: 19.99,
    category: "Category 1",
    stock: 100,
    image: "https://www.w3schools.com/tags/img_pink_flowers.jpg",
    isAddedToCart: false,
    isFavorite: true,
  },
  {
    id: 2,
    title: "Product 2",
    description: "This is the description for Product 2.",
    price: 29.99,
    category: "Category 2",
    stock: 50,
    image: "https://www.w3schools.com/tags/img_pink_flowers.jpg",
    isAddedToCart: false,
    isFavorite: false,
  },
  {
    id: 3,
    title: "Product 3",
    description: "This is the description for Product 3.",
    price: 39.99,
    category: "Category 1",
    stock: 200,
    image: "https://www.w3schools.com/tags/img_pink_flowers.jpg",
    isAddedToCart: true,
    isFavorite: false,
  },
  {
    id: 4,
    title: "Product 4",
    description: "This is the description for Product 4.",
    price: 49.99,
    category: "Category 3",
    stock: 0,
    image: "https://www.w3schools.com/tags/img_pink_flowers.jpg",
    isAddedToCart: true,
    isFavorite: false,
  },
  {
    id: 5,
    title: "Product 4",
    description: "This is the description for Product 4.",
    price: 49.99,
    category: "Category 3",
    stock: 0,
    image: "https://www.w3schools.com/tags/img_pink_flowers.jpg",
    isAddedToCart: false,
    isFavorite: false,
  },
];
